var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/design-partners/route.js")
R.c("server/chunks/1h-s_next_0xxnac6._.js")
R.c("server/chunks/[root-of-the-server]__1bh2nh1._.js")
R.c("server/chunks/1h-s_next_dist_0xo6t6b._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/node_modules__pnpm_08q1m1o._.js")
R.c("server/chunks/1c-x_zod_v4_classic_external_1lelspw.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/1h-s_next_dist_0wki3t4._.js")
R.c("server/chunks/_next-internal_server_app_api_design-partners_route_actions_0puzpkk.js")
R.m(914997)
module.exports=R.m(914997).exports
