ALTER TABLE "Chat"
ADD COLUMN IF NOT EXISTS "plan" TEXT,
ADD COLUMN IF NOT EXISTS "appSpec" JSONB,
ADD COLUMN IF NOT EXISTS "hasCode" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "AIRequestLog"
ALTER COLUMN "requestKind" SET DEFAULT 'generation';

ALTER TABLE "CreditHold"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
