var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/source-audit/route.js")
R.c("server/chunks/[root-of-the-server]__0o3qhta._.js")
R.c("server/chunks/1h-s_next_0xxnac6._.js")
R.c("server/chunks/1h-s_next_dist_esm_build_templates_app-route_0d-e31h.js")
R.c("server/chunks/1h-s_next_dist_0xo6t6b._.js")
R.c("server/chunks/node_modules__pnpm_1jxk8kz._.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/1c-x_zod_v4_classic_external_1lelspw.js")
R.c("server/chunks/1h-s_next_dist_0wki3t4._.js")
R.c("server/chunks/_next-internal_server_app_api_source-audit_route_actions_1n2uc0c.js")
R.m(895807)
module.exports=R.m(895807).exports
