var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/gallery/[publicationId]/thumbnail/route.js")
R.c("server/chunks/1h-s_next_0xxnac6._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/1h-s_next_dist_0xo6t6b._.js")
R.c("server/chunks/1h-s_next_dist_0wki3t4._.js")
R.c("server/chunks/1h-s_next_116jdfv._.js")
R.c("server/chunks/1h-s_next_01ctyx8._.js")
R.c("server/chunks/[root-of-the-server]__1r__r9k._.js")
R.c("server/chunks/1si__@better-auth_kysely-adapter_dist_index_mjs_1i2db1t._.js")
R.c("server/chunks/0dp1_kysely_dist_1720_57._.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/1zhz_@better-auth_core_dist_1hjbc40._.js")
R.c("server/chunks/0dp1_kysely_dist_0i4-u8-._.js")
R.c("server/chunks/node_modules__pnpm_08q1m1o._.js")
R.c("server/chunks/1oeh_server_app_api_gallery_[publicationId]_thumbnail_route_actions_09q5w4j.js")
R.m(117315)
module.exports=R.m(117315).exports
