var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/maintenance/gallery-thumbnails/route.js")
R.c("server/chunks/1h-s_next_dist_0p9t0as._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/[root-of-the-server]__0j1pd0l._.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/1h-s_next_dist_08_07v7._.js")
R.c("server/chunks/1h-s_next_116jdfv._.js")
R.c("server/chunks/1oeh_server_app_api_maintenance_gallery-thumbnails_route_actions_0aropa-.js")
R.m(410486)
module.exports=R.m(410486).exports
