var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/passports/[reference]/route.js")
R.c("server/chunks/[root-of-the-server]__1jfbhrn._.js")
R.c("server/chunks/1h-s_next_0xxnac6._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/1h-s_next_dist_0xo6t6b._.js")
R.c("server/chunks/[root-of-the-server]__00jrkbw._.js")
R.c("server/chunks/1c-x_zod_v4_classic_external_1lelspw.js")
R.c("server/chunks/_145blp7._.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/features_integrations_registry_ts_11ehm8e._.js")
R.c("server/chunks/1h-s_next_dist_0wki3t4._.js")
R.c("server/chunks/_next-internal_server_app_api_passports_[reference]_route_actions_1eeh4vh.js")
R.m(947914)
module.exports=R.m(947914).exports
