var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/integrations/webhooks/github/route.js")
R.c("server/chunks/1h-s_next_0xxnac6._.js")
R.c("server/chunks/1h-s_next_dist_0xo6t6b._.js")
R.c("server/chunks/[root-of-the-server]__1jcnnqs._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/1h-s_next_dist_0wki3t4._.js")
R.c("server/chunks/1c-x_zod_v4_classic_external_1lelspw.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/_next-internal_server_app_api_integrations_webhooks_github_route_actions_1j4hiy9.js")
R.m(319689)
module.exports=R.m(319689).exports
