// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/feedback" | "/audit" | "/axion-studio" | "/axon" | "/benchmarks" | "/benchmarks/screenshot-to-react" | "/blog" | "/blog/[slug]" | "/chats/[id]" | "/compare" | "/compare/[slug]" | "/contact" | "/cookies" | "/cozypaws" | "/dashboard" | "/dashboard/usage" | "/design-rocket-certificates" | "/docs/[[...slug]]" | "/example" | "/feedback" | "/forgot-password" | "/forma" | "/gallery" | "/gallery/[slug]" | "/gallery/[slug]/preview" | "/jack" | "/launch" | "/mentality" | "/mindloop" | "/prisma" | "/privacy" | "/purchase/success" | "/questly" | "/reset-password" | "/rivr" | "/search" | "/sentinel" | "/share/[id]" | "/share/v2/[messageId]" | "/share/v2/[messageId]/passport" | "/sign-in" | "/sign-up" | "/skyelite" | "/supabase" | "/terms" | "/terraelix" | "/velorah" | "/verify-email" | "/what-is-squid-agent"
type AppRouteHandlerRoutes = "/api/auth/[...all]" | "/api/create-chat" | "/api/design-partners" | "/api/enhance-prompt" | "/api/export/[messageId]" | "/api/feedback" | "/api/gallery" | "/api/gallery/[publicationId]" | "/api/gallery/[publicationId]/thumbnail" | "/api/gallery/publication" | "/api/gallery/thumbnails/backfill" | "/api/generate-code" | "/api/generation-runs/[runId]" | "/api/get-next-completion-stream-promise" | "/api/health" | "/api/integrations/oauth/[provider]/callback" | "/api/integrations/oauth/[provider]/start" | "/api/integrations/webhooks/github" | "/api/maintenance/credit-holds" | "/api/maintenance/design-partner-notifications" | "/api/maintenance/feedback-delivery" | "/api/maintenance/gallery-thumbnails" | "/api/maintenance/rate-limit-buckets" | "/api/og" | "/api/page-purchases/[sessionId]/download" | "/api/passports/[reference]" | "/api/projects/[projectId]/integrations" | "/api/projects/[projectId]/integrations/[bindingId]" | "/api/projects/[projectId]/integrations/[bindingId]/actions" | "/api/projects/[projectId]/integrations/[bindingId]/resources" | "/api/projects/[projectId]/integrations/[bindingId]/test" | "/api/projects/[projectId]/messages" | "/api/projects/[projectId]/runtime-verifications" | "/api/projects/[projectId]/supabase-setup/[interactionId]" | "/api/projects/[projectId]/versions" | "/api/projects/[projectId]/versions/[messageId]" | "/api/ready" | "/api/remix" | "/api/s3-upload" | "/api/scrape-screenshot" | "/api/search" | "/api/share-events" | "/api/source-audit" | "/api/stripe/checkout" | "/api/stripe/credits-checkout" | "/api/stripe/page-checkout" | "/api/stripe/portal" | "/api/stripe/webhook" | "/api/synthetic/launch" | "/api/user/can-create-project" | "/api/user/credits"
type PageRoutes = never
type LayoutRoutes = "/" | "/docs" | "/forgot-password" | "/reset-password" | "/sentinel" | "/share" | "/sign-in" | "/sign-up"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/feedback": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/create-chat": {}
  "/api/design-partners": {}
  "/api/enhance-prompt": {}
  "/api/export/[messageId]": { "messageId": string; }
  "/api/feedback": {}
  "/api/gallery": {}
  "/api/gallery/[publicationId]": { "publicationId": string; }
  "/api/gallery/[publicationId]/thumbnail": { "publicationId": string; }
  "/api/gallery/publication": {}
  "/api/gallery/thumbnails/backfill": {}
  "/api/generate-code": {}
  "/api/generation-runs/[runId]": { "runId": string; }
  "/api/get-next-completion-stream-promise": {}
  "/api/health": {}
  "/api/integrations/oauth/[provider]/callback": { "provider": string; }
  "/api/integrations/oauth/[provider]/start": { "provider": string; }
  "/api/integrations/webhooks/github": {}
  "/api/maintenance/credit-holds": {}
  "/api/maintenance/design-partner-notifications": {}
  "/api/maintenance/feedback-delivery": {}
  "/api/maintenance/gallery-thumbnails": {}
  "/api/maintenance/rate-limit-buckets": {}
  "/api/og": {}
  "/api/page-purchases/[sessionId]/download": { "sessionId": string; }
  "/api/passports/[reference]": { "reference": string; }
  "/api/projects/[projectId]/integrations": { "projectId": string; }
  "/api/projects/[projectId]/integrations/[bindingId]": { "projectId": string; "bindingId": string; }
  "/api/projects/[projectId]/integrations/[bindingId]/actions": { "projectId": string; "bindingId": string; }
  "/api/projects/[projectId]/integrations/[bindingId]/resources": { "projectId": string; "bindingId": string; }
  "/api/projects/[projectId]/integrations/[bindingId]/test": { "projectId": string; "bindingId": string; }
  "/api/projects/[projectId]/messages": { "projectId": string; }
  "/api/projects/[projectId]/runtime-verifications": { "projectId": string; }
  "/api/projects/[projectId]/supabase-setup/[interactionId]": { "projectId": string; "interactionId": string; }
  "/api/projects/[projectId]/versions": { "projectId": string; }
  "/api/projects/[projectId]/versions/[messageId]": { "projectId": string; "messageId": string; }
  "/api/ready": {}
  "/api/remix": {}
  "/api/s3-upload": {}
  "/api/scrape-screenshot": {}
  "/api/search": {}
  "/api/share-events": {}
  "/api/source-audit": {}
  "/api/stripe/checkout": {}
  "/api/stripe/credits-checkout": {}
  "/api/stripe/page-checkout": {}
  "/api/stripe/portal": {}
  "/api/stripe/webhook": {}
  "/api/synthetic/launch": {}
  "/api/user/can-create-project": {}
  "/api/user/credits": {}
  "/audit": {}
  "/axion-studio": {}
  "/axon": {}
  "/benchmarks": {}
  "/benchmarks/screenshot-to-react": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/chats/[id]": { "id": string; }
  "/compare": {}
  "/compare/[slug]": { "slug": string; }
  "/contact": {}
  "/cookies": {}
  "/cozypaws": {}
  "/dashboard": {}
  "/dashboard/usage": {}
  "/design-rocket-certificates": {}
  "/docs": {}
  "/docs/[[...slug]]": { "slug"?: string[]; }
  "/example": {}
  "/feedback": {}
  "/forgot-password": {}
  "/forma": {}
  "/gallery": {}
  "/gallery/[slug]": { "slug": string; }
  "/gallery/[slug]/preview": { "slug": string; }
  "/jack": {}
  "/launch": {}
  "/mentality": {}
  "/mindloop": {}
  "/prisma": {}
  "/privacy": {}
  "/purchase/success": {}
  "/questly": {}
  "/reset-password": {}
  "/rivr": {}
  "/search": {}
  "/sentinel": {}
  "/share": {}
  "/share/[id]": { "id": string; }
  "/share/v2/[messageId]": { "messageId": string; }
  "/share/v2/[messageId]/passport": { "messageId": string; }
  "/sign-in": {}
  "/sign-up": {}
  "/skyelite": {}
  "/supabase": {}
  "/terms": {}
  "/terraelix": {}
  "/velorah": {}
  "/verify-email": {}
  "/what-is-squid-agent": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/docs": never
  "/forgot-password": never
  "/reset-password": never
  "/sentinel": never
  "/share": never
  "/sign-in": never
  "/sign-up": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
