// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(main)/admin/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feedback">> = Specific
  const handler = {} as typeof import("../../app/(main)/admin/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/(main)/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/(main)/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/benchmarks/screenshot-to-react/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks/screenshot-to-react">> = Specific
  const handler = {} as typeof import("../../app/(main)/benchmarks/screenshot-to-react/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(main)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/(main)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/chats/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chats/[id]">> = Specific
  const handler = {} as typeof import("../../app/(main)/chats/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/compare/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(main)/compare/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../app/(main)/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/(main)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/(main)/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/dashboard/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/usage">> = Specific
  const handler = {} as typeof import("../../app/(main)/dashboard/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../app/(main)/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(main)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/gallery/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(main)/gallery/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/gallery/[slug]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery/[slug]/preview">> = Specific
  const handler = {} as typeof import("../../app/(main)/gallery/[slug]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../app/(main)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/mindloop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mindloop">> = Specific
  const handler = {} as typeof import("../../app/(main)/mindloop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/(main)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(main)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/(main)/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/(main)/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/supabase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supabase">> = Specific
  const handler = {} as typeof import("../../app/(main)/supabase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/(main)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../app/(main)/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/what-is-squid-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/what-is-squid-agent">> = Specific
  const handler = {} as typeof import("../../app/(main)/what-is-squid-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/axion-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/axion-studio">> = Specific
  const handler = {} as typeof import("../../app/axion-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/axon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/axon">> = Specific
  const handler = {} as typeof import("../../app/axon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cozypaws/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cozypaws">> = Specific
  const handler = {} as typeof import("../../app/cozypaws/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-rocket-certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-rocket-certificates">> = Specific
  const handler = {} as typeof import("../../app/design-rocket-certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/docs/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/example/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/example">> = Specific
  const handler = {} as typeof import("../../app/example/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forma">> = Specific
  const handler = {} as typeof import("../../app/forma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jack/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jack">> = Specific
  const handler = {} as typeof import("../../app/jack/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/launch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/launch">> = Specific
  const handler = {} as typeof import("../../app/launch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mentality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentality">> = Specific
  const handler = {} as typeof import("../../app/mentality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prisma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prisma">> = Specific
  const handler = {} as typeof import("../../app/prisma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/purchase/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/success">> = Specific
  const handler = {} as typeof import("../../app/purchase/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/questly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questly">> = Specific
  const handler = {} as typeof import("../../app/questly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rivr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rivr">> = Specific
  const handler = {} as typeof import("../../app/rivr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sentinel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sentinel">> = Specific
  const handler = {} as typeof import("../../app/sentinel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[id]">> = Specific
  const handler = {} as typeof import("../../app/share/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/v2/[messageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/v2/[messageId]">> = Specific
  const handler = {} as typeof import("../../app/share/v2/[messageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/v2/[messageId]/passport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/v2/[messageId]/passport">> = Specific
  const handler = {} as typeof import("../../app/share/v2/[messageId]/passport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/skyelite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/skyelite">> = Specific
  const handler = {} as typeof import("../../app/skyelite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terraelix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terraelix">> = Specific
  const handler = {} as typeof import("../../app/terraelix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/velorah/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/velorah">> = Specific
  const handler = {} as typeof import("../../app/velorah/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-chat">> = Specific
  const handler = {} as typeof import("../../app/api/create-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/design-partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/design-partners">> = Specific
  const handler = {} as typeof import("../../app/api/design-partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enhance-prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enhance-prompt">> = Specific
  const handler = {} as typeof import("../../app/api/enhance-prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/[messageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/[messageId]">> = Specific
  const handler = {} as typeof import("../../app/api/export/[messageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gallery/[publicationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/[publicationId]">> = Specific
  const handler = {} as typeof import("../../app/api/gallery/[publicationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gallery/[publicationId]/thumbnail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/[publicationId]/thumbnail">> = Specific
  const handler = {} as typeof import("../../app/api/gallery/[publicationId]/thumbnail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gallery/publication/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/publication">> = Specific
  const handler = {} as typeof import("../../app/api/gallery/publication/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery">> = Specific
  const handler = {} as typeof import("../../app/api/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gallery/thumbnails/backfill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/thumbnails/backfill">> = Specific
  const handler = {} as typeof import("../../app/api/gallery/thumbnails/backfill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-code">> = Specific
  const handler = {} as typeof import("../../app/api/generate-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generation-runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generation-runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/api/generation-runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/get-next-completion-stream-promise/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/get-next-completion-stream-promise">> = Specific
  const handler = {} as typeof import("../../app/api/get-next-completion-stream-promise/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/oauth/[provider]/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/oauth/[provider]/callback">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/oauth/[provider]/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/oauth/[provider]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/oauth/[provider]/start">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/oauth/[provider]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/webhooks/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/webhooks/github">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/webhooks/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/credit-holds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/credit-holds">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/credit-holds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/design-partner-notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/design-partner-notifications">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/design-partner-notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/feedback-delivery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/feedback-delivery">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/feedback-delivery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/gallery-thumbnails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/gallery-thumbnails">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/gallery-thumbnails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/rate-limit-buckets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/rate-limit-buckets">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/rate-limit-buckets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/page-purchases/[sessionId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page-purchases/[sessionId]/download">> = Specific
  const handler = {} as typeof import("../../app/api/page-purchases/[sessionId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/passports/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/passports/[reference]">> = Specific
  const handler = {} as typeof import("../../app/api/passports/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/integrations/[bindingId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/integrations/[bindingId]/actions">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/integrations/[bindingId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/integrations/[bindingId]/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/integrations/[bindingId]/resources">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/integrations/[bindingId]/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/integrations/[bindingId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/integrations/[bindingId]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/integrations/[bindingId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/integrations/[bindingId]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/integrations/[bindingId]/test">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/integrations/[bindingId]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/messages">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/runtime-verifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/runtime-verifications">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/runtime-verifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/supabase-setup/[interactionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/supabase-setup/[interactionId]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/supabase-setup/[interactionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/versions/[messageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/versions/[messageId]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/versions/[messageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[projectId]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/versions">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[projectId]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ready">> = Specific
  const handler = {} as typeof import("../../app/api/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/remix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/remix">> = Specific
  const handler = {} as typeof import("../../app/api/remix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/s3-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/s3-upload">> = Specific
  const handler = {} as typeof import("../../app/api/s3-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scrape-screenshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scrape-screenshot">> = Specific
  const handler = {} as typeof import("../../app/api/scrape-screenshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/share-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share-events">> = Specific
  const handler = {} as typeof import("../../app/api/share-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/source-audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/source-audit">> = Specific
  const handler = {} as typeof import("../../app/api/source-audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/credits-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/credits-checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/credits-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/page-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/page-checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/page-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/synthetic/launch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/synthetic/launch">> = Specific
  const handler = {} as typeof import("../../app/api/synthetic/launch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/can-create-project/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/can-create-project">> = Specific
  const handler = {} as typeof import("../../app/api/user/can-create-project/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/credits">> = Specific
  const handler = {} as typeof import("../../app/api/user/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(main)/forgot-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(main)/forgot-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/reset-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(main)/reset-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/sign-in/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/(main)/sign-in/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(main)/sign-up/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/(main)/sign-up/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sentinel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sentinel">> = Specific
  const handler = {} as typeof import("../../app/sentinel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/share">> = Specific
  const handler = {} as typeof import("../../app/share/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
