var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/design-rocket-certificates/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t77hi7._.js")
R.c("server/chunks/ssr/1h-s_next_dist_esm_build_templates_app-page_12tw8v1.js")
R.c("server/chunks/ssr/[root-of-the-server]__1gd_sil._.js")
R.c("server/chunks/ssr/1h-s_next_dist_compiled_@opentelemetry_api_index_0pecjd4.js")
R.c("server/chunks/ssr/0mts_@opentelemetry_api_build_esm_0zm6wya._.js")
R.c("server/chunks/ssr/1h-s_next_dist_0lv3zjo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oaresa._.js")
R.c("server/chunks/ssr/1h-s_next_dist_client_components_1y-viyj._.js")
R.c("server/chunks/ssr/1h-s_next_dist_client_components_builtin_forbidden_0_whicm.js")
R.c("server/chunks/ssr/1h-s_next_dist_client_components_builtin_unauthorized_11-z77q.js")
R.c("server/chunks/ssr/1h-s_next_dist_client_components_builtin_global-error_1u3k8px.js")
R.c("server/chunks/ssr/_next-internal_server_app_design-rocket-certificates_page_actions_02tmv9m.js")
R.m(413023)
module.exports=R.m(413023).exports
