var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/synthetic/launch/route.js")
R.c("server/chunks/[root-of-the-server]__1yyqob2._.js")
R.c("server/chunks/0mts_@opentelemetry_api_build_esm_16eb8kt._.js")
R.c("server/chunks/[root-of-the-server]__0i1dc05._.js")
R.c("server/chunks/_0zv28wo._.js")
R.c("server/chunks/[root-of-the-server]__0vex1ir._.js")
R.c("server/chunks/1c-x_zod_v4_classic_external_1lelspw.js")
R.c("server/chunks/_next-internal_server_app_api_synthetic_launch_route_actions_024w4u8.js")
R.m(31648)
module.exports=R.m(31648).exports
